### ISSUE TITLE
BigQueryExampleGen via DirectRunner does not seem to support REPEATED

### ISSUE THREAD

**Issue by yantriks-edi-bice** [tensorflow/tfx#1856]
Using TFX installed via

pip install --index-url https://test.pypi.org/simple/ tfx==0.22.0.dev20200525 --extra-index-url https://pypi.org/simple/

Running TFX taxi template pipeline with a query along the lines of

SELECT org_id, item_id, location_id, date,
array_agg(sales) over (partition by org_id, item_id, location_id order by unix_date(date) range BETWEEN 5 PRECEDING AND CURRENT ROW) as sales,

Using DirectRunner throws this error whereas DataflowRunner seemed to work though extremely slow and I interrupted to try DirectRunner

...

  File "/Users/edibice/PycharmProjects/markdowns-tfx-pipeline/venv/lib/python3.7/site-packages/apache_beam/io/textio.py", line 210, in read_records
    yield self._coder.decode(record)
  File "/Users/edibice/PycharmProjects/markdowns-tfx-pipeline/venv/lib/python3.7/site-packages/apache_beam/io/gcp/bigquery.py", line 570, in decode
    return self._decode_with_schema(value, self.fields)
  File "/Users/edibice/PycharmProjects/markdowns-tfx-pipeline/venv/lib/python3.7/site-packages/apache_beam/io/gcp/bigquery.py", line 587, in _decode_with_schema
    value[field.name] = converter(value[field.name])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list' [while running 'Run[BigQueryExampleGen]']

**Comment by casassg** [comment]
Seems this is due to Dataflow using the old BigQuerySource vs the new ReadFromBigQuery for Beam: https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_big_query/example_gen/executor.py#L94

BigQuerySource does support repeated fields, vs ReadFromBigQuery does not. Updated information on Beam: https://issues.apache.org/jira/browse/BEAM-10524?jql=project%20%3D%20BEAM%20AND%20text%20~%20%22bigquery%20decoder%20list%22 

Wondering if we can either extend the decoder for TFX or surface a flag to use the old BigQuerySource instead when needed. Right now this makes for inconsistent behaviour between the 2 environments. Wondering if we can allow users to choose the reader as needed (and leave defaults as is)

Alternative here is to vendor this myself and switch the reader as I need it, but would rather avoid having to do so.

**Comment by casassg** [comment]
Seems its been fixed in https://issues.apache.org/jira/browse/BEAM-10524?jql=project%20%3D%20BEAM%20AND%20text%20~%20%22bigquery%20decoder%20list%22

https://github.com/apache/beam/pull/12671

Any chance we can enable a way to manually set to use the old source if we detect issues like this (until migration is 100% done)?

**Comment by yantriks-edi-bice** [comment]
Confirming it works with latest TFX

**Comment by yantriks-edi-bice** [comment]
While it seems to run okay now and generate examples it seems from the generated schema that the nested and repeated structure is not preserved - I was expecting it to generate SequenceExample TFRecords using FeatureLists

**Comment by casassg** [comment]
[Full disclaimer, I'm not from TFX team]

I think it generates tf.example w valueList being the list of elements (as seen in https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/core/example/example.proto#L46). Nested records seems to be a whole different scope and potentially harder. Also curious on how you use nested fields on model as you may end up needing to flatten them?  

To generate SequenceExamples you may need to tell exampleGen that you want SequenceExample. Looking at the code seems it's not available for QueryBasedExampleGen yet, only for FileBasedExampleGen https://github.com/tensorflow/tfx/blob/master/tfx/components/example_gen/component.py#L143

Would be curious to learn more on what's the schema and expected output as well as recommended path from Google?

**Comment by gaikwadrahul8** [comment]
@yantriks-edi-bice 

Apologies for the delay and We have updated our official documentation about `tf.train.SequenceExample()` so kindly have a look into it [here](https://www.tensorflow.org/api_docs/python/tf/train/SequenceExample) and for your reference [here](url) is one good article so I hope it will help you to resolve your issue 

If issue still persists please let us know if possible help us with minimal code with error log so it will be easy to do investigation and find out root cause for your issue ?

If your issue got resolved, please feel free to close this issue ?

Thank you!

**Comment by gaikwadrahul8** [comment]
Closing this due to inactivity. Please take a look into above workaround, Please feel free to re-open the issue if necessary and post your comments(if you still have queries on this). Thank you!
